In [ ]:
#HOMEWORK2

#Matrix operations
#Generate a matrix A with 20 rows and 5 columns with entries being random uniform numbers on
#an interval [0, 1]. Then generate a matrix B with 5 rows and 7 columns where entries are drawn
#from a Gaussian distribution with mean 0 and variance 10. Use set.seed() function with a chosen
#seed (record the seed) for reproducibility. Type in ?set.seed in the R console to learn more about
#the function. With the two matrices compute:
#• AB (a matrix product)
#• multiply the 3rd row of A by the 4th column of B and compute the sum of entries in the resulting
#vector, then check that agrees with a corresponding term in the matrix product you computed in
#the previous part.
#• obtain a vector which is a product of matrix multiplication between matrix A and the 4th column
#of B.

In [37]:
import numpy as np
mymatrixA = np.random.rand(20, 5)#Creating the matrix [20x5] with random values in the interval [0, 1]
print('Matrix A\n')
print(mymatrixA)

mymatrixB = np.random.normal(0, 10, size=(5, 7))#Creating the matrix [5x7] mean = 0 and variance = 10
print('\nMatrix B\n')
print(mymatrixB)

product = mymatrixA @ mymatrixB #Multiplying matrix A to Matrix B
print('\nMEu resultado\n')
print(product)


print('\n3rd row x 4th colum\n')
rowxcolum = np.dot(mymatrixA[3:, ], mymatrixB[:, 4]) #multiplyin 3rd row x 4th colum
print(rowxcolum)


vector = np.dot(mymatrixA, mymatrixB[:, 4]) #mULTIPLYIN MATRIXA to matrix B 4th colum
print('\nvector final\n')
print(vector)


Matrix A

[[0.34603814 0.0534214  0.99497072 0.47175666 0.8708733 ]
 [0.40396884 0.83669719 0.7252631  0.67655148 0.65781178]
 [0.36297569 0.94292189 0.46510186 0.96311927 0.59498548]
 [0.64777722 0.8216482  0.168505   0.85386972 0.97427585]
 [0.00105812 0.82046671 0.06933409 0.32480512 0.87205277]
 [0.32288241 0.12166007 0.16390631 0.25424939 0.65054548]
 [0.15545023 0.2100546  0.81200436 0.73576462 0.27024458]
 [0.38093    0.22642917 0.71800105 0.86608445 0.36349094]
 [0.02415841 0.47567691 0.66658537 0.15544152 0.92064406]
 [0.58147707 0.02228103 0.19302893 0.94934461 0.68746398]
 [0.400823   0.21000668 0.49295531 0.9442614  0.92118817]
 [0.10329522 0.61754311 0.6767025  0.52934694 0.56461212]
 [0.51195677 0.16735497 0.5867889  0.95318952 0.3411765 ]
 [0.18204659 0.12799555 0.01358261 0.86910615 0.57873439]
 [0.81773726 0.6203448  0.18575401 0.99343331 0.0047878 ]
 [0.27217733 0.07349721 0.26172808 0.70544398 0.02858952]
 [0.26166177 0.42480735 0.40002989 0.67681423 0.03999259]
 [0.