In [15]:
#HOMEWORK2

#Matrix operations
#Generate a matrix A with 20 rows and 5 columns with entries being random uniform numbers on
#an interval [0, 1]. Then generate a matrix B with 5 rows and 7 columns where entries are drawn
#from a Gaussian distribution with mean 0 and variance 10. Use set.seed() function with a chosen
#seed (record the seed) for reproducibility. Type in ?set.seed in the R console to learn more about
#the function. With the two matrices compute:
#• AB (a matrix product)
#• multiply the 3rd row of A by the 4th column of B and compute the sum of entries in the resulting
#vector, then check that agrees with a corresponding term in the matrix product you computed in
#the previous part.
#• obtain a vector which is a product of matrix multiplication between matrix A and the 4th column
#of B.

In [16]:
import numpy as np

In [17]:
mymatrixA = np.random.rand(20, 5)#Creating the matrix [20x5] with random values in the interval [0, 1]
print('Matrix A\n')
print(mymatrixA)


Matrix A

[[0.1945276  0.6148342  0.56225923 0.25890539 0.93847917]
 [0.26103126 0.59595229 0.29333847 0.011722   0.11974585]
 [0.87386573 0.49752376 0.29097319 0.75123082 0.02442032]
 [0.07752507 0.45175605 0.79838774 0.6476587  0.01461071]
 [0.84043539 0.57350895 0.5506336  0.24554604 0.42266711]
 [0.91556714 0.46834948 0.11171359 0.69178244 0.58465411]
 [0.05247929 0.54674259 0.19649949 0.4973383  0.29687316]
 [0.36694764 0.80540036 0.52877705 0.28136415 0.64106452]
 [0.53830893 0.07994154 0.97367142 0.41631963 0.32772247]
 [0.8507728  0.5864878  0.6866187  0.62268361 0.45337955]
 [0.03750815 0.0264604  0.51853458 0.02001013 0.36639241]
 [0.40290654 0.29967473 0.40756769 0.10500243 0.64013943]
 [0.72509387 0.79738287 0.4008553  0.87410848 0.94124385]
 [0.79598104 0.28608608 0.36626369 0.82534359 0.54854997]
 [0.01510342 0.81327653 0.06669651 0.15284147 0.23106709]
 [0.87061223 0.71958985 0.58912901 0.1959103  0.53578083]
 [0.23050436 0.27991593 0.1379344  0.95738151 0.06040445]
 [0.

In [18]:
mymatrixB = np.random.normal(0, 10, size=(5, 7))#Creating the matrix [5x7] mean = 0 and variance = 10
print('\nMatrix B\n')
print(mymatrixB)


Matrix B

[[  1.34043089  -4.28884796  28.21539978   5.18600318 -24.4368002
   20.08963878  -8.61797251]
 [  3.60706018  -8.45291223  10.3452282   -3.25995141   5.29586631
   -1.44445561   0.72060238]
 [  1.13598583  -4.65161869  -4.33868168 -14.74891248   1.11779857
   -2.71163716 -10.54718407]
 [ 13.83191141  -6.32007583  23.26136882   3.47748015 -13.04233598
    4.7324319  -12.69645246]
 [ -8.07114504   9.43736596  20.71770421   8.7587809    1.66962168
  -10.9274312    6.42565346]]


In [19]:

product = mymatrixA @ mymatrixB #Multiplying matrix A to Matrix B
print('\nMEu resultado\n')
print(product)


MEu resultado

[[-8.76231728e-01 -1.42638473e+00  3.48754379e+01 -1.67949272e-01
  -2.67888580e+00 -7.53466887e+00 -4.42047224e+00]
 [ 2.02841002e+00 -6.46555306e+00  1.50111906e+01 -3.82589932e+00
  -2.84774382e+00  2.33472868e+00 -4.29339293e+00]
 [ 1.34903544e+01 -1.38242705e+01  4.65216180e+01  1.44471161e+00
  -2.81514457e+01  1.93362796e+01 -1.96224317e+01]
 [ 1.14808180e+01 -1.18203083e+01  1.87650983e+01 -1.04658161e+01
  -7.03217645e+00  1.64531449e+00 -1.68923995e+01]
 [ 3.80570231e+00 -8.57666337e+00  4.17257067e+01 -1.07642738e+00
  -1.93816273e+01  1.11058808e+01 -1.30388623e+01]
 [ 7.89336957e+00 -7.25981704e+00  5.83980827e+01  9.10020047e+00
  -2.78146496e+01  1.42990221e+01 -1.37575007e+01]
 [ 6.74873189e+00 -6.10219864e+00  2.40036524e+01 -7.86192628e-02
  -4.15809085e+00 -1.15873210e+00 -6.53762545e+00]
 [ 2.71535805e+00 -6.56971267e+00  3.62177300e+01 -1.92807884e+00
  -6.70997786e+00 -8.99022792e-01 -7.61214820e+00]
 [ 5.22939747e+00 -7.05194690e+00  2.82649864e+0

In [22]:
print('\n3rd row x 4th colum\n')
#rowxcolum = np.dot(mymatrixA[3:, ], mymatrixB[:, 4]) #multiplyin 3rd row x 4th colum
# mymatrixA[3] @ 
rowxcolum = mymatrixA[3] @  mymatrixB[:,4]
print(rowxcolum)



3rd row x 4th colum

-7.032176453167937


In [21]:

vector = np.dot(mymatrixA, mymatrixB[:, 4]) #mULTIPLYIN MATRIXA to matrix B 4th colum
print('\nvector final\n')
print(vector)


vector final

[ -2.6788858   -2.84774382 -28.15144566  -7.03217645 -19.38162727
 -27.81464959  -4.15809085  -6.70997786 -16.52542741 -24.28097916
   0.15392668  -8.10381695 -22.87696079 -27.37528441   2.40486259
 -18.46617465 -16.38184744 -21.07762447 -30.00631593  -2.54684969]
